hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "576f429a1be6eaca9eccc14adc28885a077142c0d0dbb62b182c1790bc8fa497"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "c704558740d92fc998a5d17fac0fe9c7710865550842b2308fdc75eafe4adc25"

[[files]]
file = "config/lithium.properties"
hash = "db94b9e5ecf1ae0b3dd0c8312bb4602bcf4bab2a4c54fdebac2c87206a99d939"

[[files]]
file = "config/modmenu.json"
hash = "8b36ea8af428943d85a7594b9d2e8144be3f77bab05a150e8b2db4dbe8f25a37"

[[files]]
file = "config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "8b36ea8af428943d85a7594b9d2e8144be3f77bab05a150e8b2db4dbe8f25a37"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/options.txt"
hash = "88a4b9df8024bfb56294ee78b9c85e569f35c66cc9f14e88284512335a3638d2"

[[files]]
file = "mods/almanac.pw.toml"
hash = "2954a09b866a84faea38e04bdce0be1a5961d456fbc2b4ef85be6d3fb212a4f7"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "136391df5c5b9d24f49bfd3536d81cae0ca92c3c3f3fbc898b3f925b5a3f4695"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "79103819dc5156e7cc6d85da4796f179db2c45780ab4875c0066f6724b73522d"
metafile = true

[[files]]
file = "mods/chunky-player-pause.pw.toml"
hash = "3a6ae7b2a7480a6105424bcf63533749e99f819f717c6f55f210a103a7bc0352"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "371826e1a7a56f2321b2e1387dfffa35a90bf4852e0e2e30130543799fe92155"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "92a6548a71aafac283544df4eb0af625cb6b2a90fd79d027ed092ea420e1d011"
metafile = true

[[files]]
file = "mods/disconnect-packet-fix.pw.toml"
hash = "5a42b13a84055aa5fc4991922853994803a3443bbaad3f21fa233991e98ee8e7"
metafile = true

[[files]]
file = "mods/enchanter-fix.pw.toml"
hash = "df152d566d9b6573b0dc8cee1c79bc7dbf0db6a0b82564eb2072970b50bbb475"
metafile = true

[[files]]
file = "mods/entity-view-distance.pw.toml"
hash = "6d92041da75bd6ae38e5ee03e012de913e4d05f696c97737fb610e0db262fb9f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d2cccb8361da8192d2a62efa56688b9f1f22b50dbf79ea0753c114650a389d87"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "0ed9039229bd7f82ac7d1e738aacc58abf89294c0723568d08dedd5a88100836"
metafile = true

[[files]]
file = "mods/fixmcstats.pw.toml"
hash = "14537b562b39ce077413feaecebdac72e8a55d9e89c37e5778f95eade8392d66"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "319a9d8154d5d514abcc9e96138707282db71706ea7c7bb0dd2bfd91be5dd105"
metafile = true

[[files]]
file = "mods/jukebox-custom-disc-fix.pw.toml"
hash = "f2a027fa0f89046499d1a585b1459a2deb762e1fa4e95f4c88a30f8b3055e80b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "b43d4bbca126353c53443e8e5c2b39442581b45b7b1666db33f3fea3f276c0b5"
metafile = true

[[files]]
file = "mods/kryptonfnp-patcher.pw.toml"
hash = "81de13ddb1b749588e2f429a76d72a383081708c4491f3a153e80c3e83355e57"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "513b2fc6e7e09413b520926dfa50f751e5fbc32802478c26e2cb8fcffc4c48b8"
metafile = true

[[files]]
file = "mods/limitless-banners.pw.toml"
hash = "162de615e97387eb6ba3ffa54089f512f4a172b5d56bb8437659397f1c22a5a6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b6efacd12d0465fc627699d790d52a970f0f8a6c22f632160390a3551aa31506"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "b791120d403d6741fbe1679263dc93b867694fa80ab46c474924fe2db3c2d864"
metafile = true

[[files]]
file = "mods/ly-clumps.pw.toml"
hash = "ae082d8d538cafdec354a7ab22dae10a81bfa9abb19a8e4e2838d9dbca4a74a6"
metafile = true

[[files]]
file = "mods/mc-258859.pw.toml"
hash = "c67f9ce59bb82324561abfc05bec415a82e43ca06b52f355924cc1ede578a340"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "5fff7430873650ec070bc4cd66d3519ec68e6ec1d2178ce484c84f017af6a1c6"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "fad63c017628623dc2128412c8a03a63ad25c3beb5b9db2cdb0dcd5034c1d329"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "0c62a93a7a5b981adfaf83693e00ed3c7429c0cc721c89499649826fe49f5ea3"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "85bdc238f6a1c70d5572d9abe88f971a6c6289b5b38f8fb90270709024d25e10"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "49c89ba461c7d9ea6ac1c54ad9f08d0ea5706f39980ebb18ec728342a8826987"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "26a5b18bb371618aefa520c9974bc4cbc59ac86fd22d76a264e8cf3dd5e822ba"
metafile = true

[[files]]
file = "mods/skeleton-ai-fix.pw.toml"
hash = "706278655f952c8f4a595321f48c4da178e9cd74b41cd6603b81b4a25b4969f6"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "971978c7cbbbd20451d66a88bc11e4165eb83b2a94e49bb9a6a73b38049b3f13"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "30f7f3696e76859307cbf39c80861256788d41f6303103943954256d7a1b6b75"
metafile = true

[[files]]
file = "mods/vertigo.pw.toml"
hash = "18bf2317d6195b45056d548e189e3feac0e5f54e600ff84888dd3deb53b9ace3"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "9f2d007aaee71de8fa17a80d50d00041f4618221ff33c8bd280a335999319854"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64e9e11f2990bdf01c50b962870b1f974b3ca3f7fa0dd098c3ed6fdd951771b4"
metafile = true
