name = "Kvantik adventures"
author = "azikx"
version = "0.0.1"
description = "unstable modpack for my server..."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1040212b2735acbba82b4690d1a28cd8e070506f5025b797a1572f0b894effb8"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
